# Generated by Django 2.2.7 on 2020-07-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
