# Generated by Django 2.2.7 on 2020-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_auto_20200621_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='group',
            field=models.CharField(default=0, max_length=2, verbose_name='Group'),
        ),
    ]
