# Generated by Django 2.2.7 on 2020-06-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200621_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='gender',
            field=models.CharField(default='Male', max_length=9, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='dob',
            field=models.CharField(default='1997', max_length=100, verbose_name='DOB'),
        ),
    ]
