# Generated by Django 2.2.7 on 2020-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_userlogin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='education',
            field=models.CharField(default='1997', max_length=100, verbose_name='Education'),
        ),
    ]
