# Generated by Django 2.2.7 on 2020-06-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_userlogin_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='domain',
            field=models.CharField(default='0', max_length=10, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='similarity',
            field=models.CharField(default='0', max_length=10, verbose_name='Similarity'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='education',
            field=models.CharField(default='0', max_length=10, verbose_name='Education'),
        ),
    ]
