# Generated by Django 2.2.7 on 2020-06-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_auto_20200626_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='gender',
            field=models.CharField(default='1', max_length=9, verbose_name='Gender'),
        ),
    ]
